### ISSUE TITLE
server access logの要否検討

### ISSUE THREAD

**Issue by yumetodo** [AinoMegumi/CalendarServer#20]
https://github.com/expressjs/morgan を用いることで用意にApache形式のアクセスログを出すことができる。それが必要か検討する

**Comment by AinoMegumi** [comment]
できることが、日付の変換やボーダーの取得しかできないため必要性に乏しいと考えている

**Comment by yumetodo** [comment]
nginxなりIISのログがあれば十分という理論はあるといえばある

**Comment by AinoMegumi** [comment]
独自のログは不要と判断
