### ISSUE TITLE
カバレッジの取得

### ISSUE THREAD

**Issue by yumetodo** [AinoMegumi/CalendarServer#22]
avaはc8を用いることでカバレッジを取得できる。

https://github.com/bcoe/c8

c8はreporterとしてlcovを選べる。

https://istanbul.js.org/docs/advanced/alternative-reporters/#lcov

そこで、　https://coveralls.io にそれを送信することを提案する

送信には以下のgithub actionsが利用できる。

https://github.com/marketplace/actions/coveralls-github-action

**Comment by AinoMegumi** [comment]
カバレッジ取得を行ったことで分かった存在しなかったテストケースの作成は #30 で実施する

**Comment by yumetodo** [comment]
カバレッジの継続的な取得と公開(coveralls.io)が終わっていないように見える

**Comment by yumetodo** [comment]
https://github.com/bcoe/c8/issues/71 が参考になりそう。

**Comment by AinoMegumi** [comment]
a789d2f と bc4a1a3 の作業で取得・公開作業完了
