### ISSUE TITLE
client: query paramの組み立てを単なる文字列結合で行っている

### ISSUE THREAD

**Issue by yumetodo** [AinoMegumi/CalendarServer#23]
ユーザー入力を無検査で文字列結合している。文字列結合で安全であることを保証するか、URLSearchParamsを利用するとよい

**Comment by yumetodo** [comment]
0c456c655d365c07d47dd3cca8ffe2b350eea02a こっちでは？

**Comment by yumetodo** [comment]
確認しました

**Comment by AinoMegumi** [comment]
0c456c6 で行ったサーバー仕様変更によるアップデートの際に一緒に実施
