### ISSUE TITLE
bitbucket-pipelineからgithub actionへの移行

### ISSUE THREAD

**Issue by AinoMegumi** [AinoMegumi/CalendarServer#7]

**Comment by yumetodo** [comment]
slackより

> Issue 7について
SSHの秘密鍵どうやって上げるん？

- [shimataro/ssh-key-action: GitHub Action that installs SSH key to .ssh](https://github.com/shimataro/ssh-key-action)
- [GitHub ActionsでSSHを使う - Qiita](https://qiita.com/shimataro999/items/b05a251c93fe6843cc16)

**Comment by yumetodo** [comment]
https://github.com/AinoMegumi/CalendarServer/actions/runs/2682491343 通過していそう

**Comment by yumetodo** [comment]
[Rsync Deployments Action · Actions · GitHub Marketplace](https://github.com/marketplace/actions/rsync-deployments-action)

**Comment by AinoMegumi** [comment]
https://github.com/AinoMegumi/CalendarServer/actions/runs/2682500916

問題なく通過し、デプロイも問題ないことを確認したので完了
![image](https://user-images.githubusercontent.com/11565880/179364205-442d9451-0f11-4403-b5c7-beadb2ccb7e5.png)
